### ISSUE TITLE
Invalid regular expression: /*/: Nothing to repeat

### ISSUE THREAD

**Issue by ItsEcholot** [MobileheadHolding/github-action-purge-packages#1]
```
(node:3218) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /*/: Nothing to repeat
    at RegExp (<anonymous>)
    at run (/home/runner/work/_actions/MobileheadHolding/github-action-purge-packages/1.0.4/dist/index.js:3388:20)
(node:3218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3218) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

using the following workflow step:
```yaml
    - name: purge old packages
      uses: MobileheadHolding/github-action-purge-packages@1.0.4
      with:
        owner: ItsEcholot
        days-old: 0
        version-regex: '*'
        package-name-query: 'frontend'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGES_TOKEN }}
```
